name: Test

on:
  pull_request:
    branches:
      - "**"
  workflow_call:

jobs:
  cancel-previous-runs:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous redundant runs
        # Don't cancel previous runs on main so all commits are tested and deployable.
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  test-lint:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup_node
      - name: Run linter
        run: npm run lint

  test-typecheck:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup_node
      - name: Run typecheck
        run: npm run typecheck

  test-and-build:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup_node
      - name: Run tests
        run: npm run test
